(() => {
  let pending={shapeType:null};
  function area(shape,p){const w=Number(p.widthM),h=Number(p.heightM),d=Number(p.diameterM);if(shape==='circle'){const dia=d>0?d:(w>0&&h>0?(w+h)/2:NaN);return dia>0?Math.PI*(dia/2)**2:null}if(shape==='oval')return w>0&&h>0?Math.PI*(w/2)*(h/2):null;if(shape==='triangle')return w>0&&h>0?.5*w*h:null;if(['polygon','freeform'].includes(shape))return Number.isFinite(Number(p.polygonAreaM2))?Number(p.polygonAreaM2):null;return w>0&&h>0?w*h:null}
  function quality(p){let q=Number(p.qualityScore);if(Number.isFinite(q))return Math.max(0,Math.min(100,Math.round(q)));q=70;if(p.lidar===true)q+=18;if((p.source||'').includes('SceneDepth'))q+=8;if(Number.isFinite(Number(p.distanceM))&&Number(p.distanceM)>12)q-=12;return Math.max(0,Math.min(100,Math.round(q)))}
  function normalize(p){if(!p||p.verified!==true)throw new Error('Doğrulanmamış ölçüm reddedildi');const shape=p.shapeType||pending.shapeType||'horizontal-rectangle',q=quality(p);if(p.lidar===true&&q<55)throw new Error('LiDAR derinlik kalitesi yetersiz');const a=area(shape,p);return{...p,shapeType:shape,areaM2:a,measurementQualityScore:q,accepted:true,acceptedAt:new Date().toISOString()}}
  function submitVerified(p){const r=normalize(p);window.dispatchEvent(new CustomEvent('tabela:measurement',{detail:r}));return r}
  function capability(){if(window.webkit?.messageHandlers?.tabelaMetric)return{available:true,platform:'ios'};if(window.TabelaAndroidMetric?.requestMeasurement)return{available:true,platform:'android'};return{available:false,platform:'web'}}
  function request(payload={}){pending={...payload};const c=capability();if(!c.available){window.dispatchEvent(new CustomEvent('tabela:measurement-unavailable',{detail:{reason:'native_bridge_required'}}));return false}if(c.platform==='ios')window.webkit.messageHandlers.tabelaMetric.postMessage(payload);else window.TabelaAndroidMetric.requestMeasurement(JSON.stringify(payload));return true}
  window.TabelaMetric={area,quality,normalize,submitVerified,capability,request,version:'11.0-quality'};
})();