(() => {
  const DB='tabela_ai_v11',VER=1,REC='records',PH='photos',AUD='audit',Q='queue';
  let dbp=null;
  function db(){if(dbp)return dbp;dbp=new Promise((ok,fail)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(REC))d.createObjectStore(REC,{keyPath:'id'});if(!d.objectStoreNames.contains(PH))d.createObjectStore(PH,{keyPath:'id'});if(!d.objectStoreNames.contains(AUD)){const s=d.createObjectStore(AUD,{keyPath:'auditId'});s.createIndex('recordId','recordId')}if(!d.objectStoreNames.contains(Q))d.createObjectStore(Q,{keyPath:'queueId'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)});return dbp}
  async function tx(store,mode,fn){const d=await db();return new Promise((ok,fail)=>{const t=d.transaction(store,mode),s=t.objectStore(store);let result;try{result=fn(s)}catch(e){fail(e);return}t.oncomplete=()=>ok(result);t.onerror=()=>fail(t.error)})}
  async function getAll(store){const d=await db();return new Promise((ok,fail)=>{const r=d.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>fail(r.error)})}
  const aid=()=>`A-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;const qid=()=>`Q-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
  async function audit(recordId,action,before,after,actor='field-device'){await tx(AUD,'readwrite',s=>s.put({auditId:aid(),recordId,action,before:before||null,after:after||null,actor,at:new Date().toISOString()}))}
  async function list(){return(await getAll(REC)).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))}
  async function get(id){const d=await db();return new Promise((ok,fail)=>{const r=d.transaction(REC,'readonly').objectStore(REC).get(id);r.onsuccess=()=>ok(r.result||null);r.onerror=()=>fail(r.error)})}
  async function add(record,photoData){await tx(REC,'readwrite',s=>s.put(record));if(photoData)await tx(PH,'readwrite',s=>s.put({id:record.id,data:photoData,at:new Date().toISOString()}));await audit(record.id,'create',null,record);await enqueue({type:'upsert',record});return record}
  async function update(id,patch,actor='field-device'){const before=await get(id);if(!before)throw new Error('record_not_found');const after={...before,...patch,updatedAt:new Date().toISOString()};await tx(REC,'readwrite',s=>s.put(after));await audit(id,'update',before,after,actor);await enqueue({type:'upsert',record:after});return after}
  async function remove(id,actor='field-device'){const before=await get(id);await tx(REC,'readwrite',s=>s.delete(id));await tx(PH,'readwrite',s=>s.delete(id));await audit(id,'delete',before,null,actor);await enqueue({type:'delete',id});return true}
  async function photo(id){const d=await db();return new Promise((ok,fail)=>{const r=d.transaction(PH,'readonly').objectStore(PH).get(id);r.onsuccess=()=>ok(r.result?.data||null);r.onerror=()=>fail(r.error)})}
  async function audits(recordId){const d=await db();return new Promise((ok,fail)=>{const s=d.transaction(AUD,'readonly').objectStore(AUD),i=s.index('recordId'),r=i.getAll(recordId);r.onsuccess=()=>ok((r.result||[]).sort((a,b)=>a.at.localeCompare(b.at)));r.onerror=()=>fail(r.error)})}
  async function enqueue(item){return tx(Q,'readwrite',s=>s.put({...item,queueId:qid(),queuedAt:new Date().toISOString()}))}
  async function queue(){return getAll(Q)}
  async function clearQueue(ids){return tx(Q,'readwrite',s=>{for(const id of ids)s.delete(id)})}
  async function sync(endpoint){if(!endpoint)return{ok:false,reason:'endpoint_missing'};endpoint=endpoint.replace(/\/$/,'');const q=await queue(),done=[],failed=[];for(const item of q){try{const url=item.type==='delete'?`${endpoint}/api/signs/${encodeURIComponent(item.id)}`:`${endpoint}/api/signs`,r=await fetch(url,{method:item.type==='delete'?'DELETE':'POST',headers:{'content-type':'application/json'},body:item.type==='delete'?undefined:JSON.stringify(item.record)});if(!r.ok)throw new Error(String(r.status));done.push(item.queueId)}catch(e){failed.push({queueId:item.queueId,error:e.message})}}if(done.length)await clearQueue(done);return{ok:failed.length===0,sent:done.length,left:failed.length,failed}}
  function csv(rows){const cols=['id','createdAt','project','signType','shapeLabel','ocr','ocrConfidence','ocrValidated','qualityScore','panel','lettering','address','heading','latitude','longitude','gpsAccuracy','measurementVerified','measurementSource','measurementQuality','widthM','heightM','diameterM','areaM2','distanceM','duplicateScore'];const e=v=>'"'+String(v??'').replaceAll('"','""')+'"';return'\ufeff'+[cols.join(','),...rows.map(r=>cols.map(k=>{const m={latitude:r.gps?.lat,longitude:r.gps?.lng,gpsAccuracy:r.gps?.accuracy,address:r.address?.displayName,heading:r.orientation?.heading,measurementQuality:r.measurementQualityScore};return e(k in m?m[k]:r[k])}).join(','))].join('\n')}
  function download(name,text,type){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
  async function exportCSV(){download('tabela_ai_v11.csv',csv(await list()),'text/csv;charset=utf-8')}
  async function exportJSON(){download('tabela_ai_v11.json',JSON.stringify(await list(),null,2),'application/json')}
  async function clear(){const d=await db();for(const n of [REC,PH,AUD,Q])await new Promise((ok,fail)=>{const r=d.transaction(n,'readwrite').objectStore(n).clear();r.onsuccess=()=>ok();r.onerror=()=>fail(r.error)})}
  window.TabelaStorage={list,get,add,update,remove,photo,audits,audit,queue,sync,exportCSV,exportJSON,clear,version:'11.0-indexeddb'};
})();