(() => {
  let worker=null,workerPromise=null;
  const load=src=>new Promise((ok,fail)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=fail;i.src=src});
  const cv=(w,h)=>{const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const clean=s=>(s||'').replace(/[|_~`^]+/g,' ').replace(/[“”]/g,'"').replace(/\s+/g,' ').replace(/^[^A-Za-zÇĞİÖŞÜçğıöşü0-9]+|[^A-Za-zÇĞİÖŞÜçğıöşü0-9]+$/g,'').trim();
  function normalize(s){const t=clean(s),p=t.split(/\s+/).filter(Boolean);if(p.length>=3&&p.filter(x=>/^[A-Za-zÇĞİÖŞÜçğıöşü0-9]{1,2}$/.test(x)).length/p.length>.7&&p.join('').length<42)return p.join('');return t}
  const key=s=>normalize(s).toLocaleUpperCase('tr-TR').replace(/[^A-ZÇĞİÖŞÜ0-9]/g,'');
  const alphaRatio=s=>{const a=[...(s||'')],n=a.filter(ch=>/[A-Za-zÇĞİÖŞÜçğıöşü0-9]/.test(ch)).length;return n/Math.max(1,a.length)};
  function clampBox(b,W,H){const x=clamp(b.x||0,0,W-1),y=clamp(b.y||0,0,H-1);return{x,y,w:Math.max(1,Math.min(W-x,b.w||W)),h:Math.max(1,Math.min(H-y,b.h||H))}}
  function crop(img,b,scale=2){b=clampBox(b,img.width,img.height);const c=cv(b.w*scale,b.h*scale),x=c.getContext('2d');x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.drawImage(img,b.x,b.y,b.w,b.h,0,0,c.width,c.height);return c}
  function rotate(src,deg){if(!deg)return src;const c=cv(src.width,src.height),x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.translate(c.width/2,c.height/2);x.rotate(deg*Math.PI/180);x.drawImage(src,-src.width/2,-src.height/2);return c}
  function mask(src,type){if(!['circle','oval'].includes(type))return src;const c=cv(src.width,src.height),x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.save();x.beginPath();x.ellipse(c.width/2,c.height/2,c.width*.47,c.height*.47,0,0,Math.PI*2);x.clip();x.drawImage(src,0,0);x.restore();return c}
  function enhance(src,mode){const c=cv(src.width,src.height),x=c.getContext('2d',{willReadFrequently:true});x.drawImage(src,0,0);const im=x.getImageData(0,0,c.width,c.height),d=im.data;let mean=0;for(let i=0;i<d.length;i+=4)mean+=.299*d[i]+.587*d[i+1]+.114*d[i+2];mean/=Math.max(1,d.length/4);for(let i=0;i<d.length;i+=4){let g=.299*d[i]+.587*d[i+1]+.114*d[i+2];g=clamp((g-mean)*(mode==='strong'?2.3:1.8)+128,0,255);if(mode==='binary')g=g>145?255:0;d[i]=d[i+1]=d[i+2]=g}x.putImageData(im,0,0);return c}
  async function ensure(onProgress){if(worker)return worker;if(workerPromise)return workerPromise;if(!window.Tesseract)throw new Error('OCR motoru yüklenemedi');workerPromise=Tesseract.createWorker('tur+eng',1,{logger:m=>{if(onProgress&&typeof m.progress==='number')onProgress(Math.round(m.progress*100),m.status||'OCR')}}).then(w=>{worker=w;return w});return workerPromise}
  async function prewarm(){try{await ensure();return true}catch{return false}}
  async function rec(w,img,psm,tag){await w.setParameters({tessedit_pageseg_mode:String(psm),preserve_interword_spaces:'1',user_defined_dpi:'300',tessedit_char_whitelist:"ABCDEFGHIJKLMNOPQRSTUVWXYZÇĞİÖŞÜabcdefghijklmnopqrstuvwxyzçğıöşü0123456789&+.-/' "});const r=await w.recognize(img);const text=normalize(r?.data?.text||''),confidence=Number(r?.data?.confidence||0);return{text,key:key(text),confidence,tag}}
  function lev(a,b){a=a||'';b=b||'';const d=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=d[0];d[0]=i;for(let j=1;j<=b.length;j++){const tmp=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=tmp}}return d[b.length]}
  const sim=(a,b)=>1-lev(a,b)/Math.max(1,a.length,b.length);
  const good=r=>r&&r.key.length>=3&&r.key.length<=42&&alphaRatio(r.text)>=.72&&r.confidence>=8;
  function select(cands){const usable=cands.filter(good);if(!usable.length)return{best:{text:'',key:'',confidence:0},score:0,validated:false,consensus:0};const groups=[];for(const r of usable){let g=groups.find(x=>x.key===r.key);if(!g){g={key:r.key,items:[]};groups.push(g)}g.items.push(r)}for(const g of groups){g.items.sort((a,b)=>b.confidence-a.confidence);g.best=g.items[0];g.count=new Set(g.items.map(i=>i.tag)).size;g.rank=g.best.confidence+(g.count-1)*15+Math.min(12,g.key.length*.6)}groups.sort((a,b)=>b.rank-a.rank);let g=groups[0],score=Math.min(89,Math.round(g.best.confidence*.72+Math.min(20,g.key.length)));if(g.count>=2&&g.best.confidence>=70)score=100;else if(g.count>=2&&g.best.confidence>=52)score=Math.min(97,84+Math.round((g.best.confidence-52)*.45));if(g.count<2&&groups[1]&&sim(g.key,groups[1].key)>.88)score=Math.max(score,90);return{best:g.best,score,validated:score>=92,consensus:g.count}}
  function bands(sign,type){const arr=[];const H=sign.height,W=sign.width;const fractions=type==='vertical-rectangle'?[.18,.38,.58,.76]:[.27,.43,.58,.72];for(const cy of fractions){const bh=H*((type==='circle'||type==='oval')?.26:.22);arr.push({x:W*.05,y:H*cy-bh/2,w:W*.9,h:bh})}return arr}
  async function run(photoData,shape,onProgress){const img=await load(photoData),w=await ensure(onProgress);let b=shape?.bbox||{x:img.width*.08,y:img.height*.14,w:img.width*.84,h:img.height*.72};let sign=mask(crop(img,b,1.65),shape?.shapeType);const cands=[];const bs=bands(sign,shape?.shapeType);let step=0;for(let i=0;i<bs.length;i++){const base=crop(sign,bs[i],2.2);for(const job of [{img:base,psm:7,t:'raw'},{img:enhance(base,'normal'),psm:7,t:'contrast'},{img:enhance(base,'binary'),psm:8,t:'binary'}]){step++;onProgress?.(Math.min(75,12+step*5),`OCR ${step}`);const r=await rec(w,job.img,job.psm,`${i}-${job.t}`);if(good(r))cands.push(r)}}let pick=select(cands);if(!pick.validated){const preferred=cands.slice().sort((a,b)=>b.confidence-a.confidence)[0];const bi=preferred?Number(preferred.tag.split('-')[0]):1;const base=crop(sign,bs[clamp(bi,0,bs.length-1)],2.35);for(const a of [-10,-6,6,10]){for(const mode of ['normal','binary']){onProgress?.(82,'eğim doğrulama');const r=await rec(w,enhance(rotate(base,a),mode),7,`rot${a}-${mode}`);if(good(r))cands.push(r)}}pick=select(cands)}const unique=[],seen=new Set();for(const r of cands.sort((a,b)=>b.confidence-a.confidence)){if(!seen.has(r.key)){seen.add(r.key);unique.push(r)}}onProgress?.(100,pick.validated?'doğrulandı':'kontrol gerekli');return{text:pick.best.text,confidence:pick.score,rawConfidence:Math.round(pick.best.confidence||0),validated:pick.validated,consensus:pick.consensus,candidates:unique.slice(0,5),version:'10.0'} }
  window.TabelaOCR={run,prewarm,version:'10.0'};
})();