(() => {
  let worker=null,workerPromise=null;
  const loadImage=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src;});
  const cv=(w,h)=>{const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c;};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function clampBox(b,W,H){const x=clamp(b.x||0,0,W-1),y=clamp(b.y||0,0,H-1);return{x,y,w:Math.max(1,Math.min(W-x,b.w||W)),h:Math.max(1,Math.min(H-y,b.h||H))};}
  function crop(img,b,scale=2){b=clampBox(b,img.width,img.height);const c=cv(b.w*scale,b.h*scale),x=c.getContext('2d');x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.drawImage(img,b.x,b.y,b.w,b.h,0,0,c.width,c.height);return c;}
  function maskSign(src,type){if(!['circle','oval'].includes(type))return src;const c=cv(src.width,src.height),x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.save();x.beginPath();x.ellipse(c.width/2,c.height/2,c.width*.47,c.height*.47,0,0,Math.PI*2);x.clip();x.drawImage(src,0,0);x.restore();return c;}
  function rotate(src,deg){if(!deg)return src;const c=cv(src.width,src.height),x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.translate(c.width/2,c.height/2);x.rotate(deg*Math.PI/180);x.drawImage(src,-src.width/2,-src.height/2);return c;}
  function grayscaleData(src){const x=src.getContext('2d',{willReadFrequently:true}),im=x.getImageData(0,0,src.width,src.height),d=im.data,g=new Uint8Array(src.width*src.height);for(let i=0,p=0;i<d.length;i+=4,p++)g[p]=Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]);return g;}
  function otsu(g){const hist=new Uint32Array(256);for(const v of g)hist[v]++;const total=g.length;let sum=0;for(let i=0;i<256;i++)sum+=i*hist[i];let sumB=0,wB=0,best=127,max=0;for(let t=0;t<256;t++){wB+=hist[t];if(!wB)continue;const wF=total-wB;if(!wF)break;sumB+=t*hist[t];const mB=sumB/wB,mF=(sum-sumB)/wF,between=wB*wF*(mB-mF)*(mB-mF);if(between>max){max=between;best=t;}}return best;}
  function enhance(src,mode='contrast'){const c=cv(src.width,src.height),x=c.getContext('2d',{willReadFrequently:true});x.drawImage(src,0,0);const im=x.getImageData(0,0,c.width,c.height),d=im.data;let mean=0;for(let i=0;i<d.length;i+=4)mean+=.299*d[i]+.587*d[i+1]+.114*d[i+2];mean/=Math.max(1,d.length/4);let gray=null,thr=145;if(mode==='otsu'){gray=new Uint8Array(c.width*c.height);for(let i=0,p=0;i<d.length;i+=4,p++){let g=.299*d[i]+.587*d[i+1]+.114*d[i+2];g=clamp((g-mean)*1.65+128,0,255);gray[p]=g;}thr=otsu(gray);}for(let i=0,p=0;i<d.length;i+=4,p++){let g=gray?gray[p]:.299*d[i]+.587*d[i+1]+.114*d[i+2];if(!gray)g=clamp((g-mean)*(mode==='threshold'?2.25:1.9)+128,0,255);if(mode==='threshold'||mode==='otsu')g=g>thr?255:0;d[i]=d[i+1]=d[i+2]=g;}x.putImageData(im,0,0);return c;}
  function clean(s){return(s||'').replace(/[|_~`^]+/g,' ').replace(/[“”]/g,'"').replace(/\s+/g,' ').replace(/^[^A-Za-zÇĞİÖŞÜçğıöşü0-9]+|[^A-Za-zÇĞİÖŞÜçğıöşü0-9]+$/g,'').trim();}
  function normalize(s){const t=clean(s),p=t.split(/\s+/).filter(Boolean);if(p.length>=3&&p.filter(x=>/^[A-Za-zÇĞİÖŞÜçğıöşü0-9]{1,2}$/.test(x)).length/p.length>.72&&p.join('').length<=40)return p.join('');return t;}
  function key(s){return normalize(s).toLocaleUpperCase('tr-TR').replace(/[^A-ZÇĞİÖŞÜ0-9]/g,'');}
  function alphaRatio(s){const a=[...(s||'')],n=a.filter(ch=>/[A-Za-zÇĞİÖŞÜçğıöşü0-9]/.test(ch)).length;return n/Math.max(1,a.length);}
  async function ensure(onProgress){if(worker)return worker;if(workerPromise)return workerPromise;if(!window.Tesseract)throw new Error('OCR motoru yüklenemedi. İnternet bağlantısını kontrol edin.');workerPromise=Tesseract.createWorker('tur+eng',1,{logger:m=>{if(onProgress&&typeof m.progress==='number')onProgress(Math.round(m.progress*100),m.status||'hazırlanıyor')}}).then(w=>{worker=w;return w});return workerPromise;}
  async function prewarm(){try{await ensure();return true}catch{return false}}
  function parseTSV(tsv){if(!tsv)return[];const rows=tsv.split(/\r?\n/).filter(Boolean);if(rows.length<2)return[];const h=rows[0].split('\t'),ix=n=>h.indexOf(n),out=[];for(const row of rows.slice(1)){const a=row.split('\t');if(Number(a[ix('level')])!==5)continue;const text=clean(a.slice(ix('text')).join(' ')),conf=Number(a[ix('conf')]);if(!text||!Number.isFinite(conf)||conf<8)continue;out.push({text,conf,left:+a[ix('left')],top:+a[ix('top')],width:+a[ix('width')],height:+a[ix('height')],block:a[ix('block_num')],par:a[ix('par_num')],line:a[ix('line_num')]});}return out;}
  function insideShape(cx,cy,W,H,type){if(!['circle','oval'].includes(type))return true;const nx=(cx-W/2)/(W*.47),ny=(cy-H/2)/(H*.47);return nx*nx+ny*ny<=1;}
  function groupLines(words,W,H,type){const m=new Map();for(const w of words){const cx=w.left+w.width/2,cy=w.top+w.height/2;if(!insideShape(cx,cy,W,H,type))continue;const k=`${w.block}:${w.par}:${w.line}`;if(!m.has(k))m.set(k,[]);m.get(k).push(w);}const lines=[];for(const ws of m.values()){ws.sort((a,b)=>a.left-b.left);let l=Infinity,t=Infinity,r=-1,b=-1,cs=0;for(const w of ws){l=Math.min(l,w.left);t=Math.min(t,w.top);r=Math.max(r,w.left+w.width);b=Math.max(b,w.top+w.height);cs+=w.conf;}const text=normalize(ws.map(x=>x.text).join(' ')),k=key(text);if(k.length<3||k.length>40)continue;const width=r-l,height=b-t,cx=(l+r)/2,cy=(t+b)/2,avg=cs/ws.length,wr=width/W,hr=height/H,center=1-Math.min(1,Math.hypot((cx-W/2)/(W/2),(cy-H/2)/(H/2))/1.414),edge=Math.min(l,t,W-r,H-b),punct=1-alphaRatio(text);let score=avg+center*28+Math.min(18,k.length*1.2)+Math.min(14,wr*22)-punct*35;if(hr<.025||hr>.55)score-=18;if(wr<.07)score-=10;if(edge<Math.min(W,H)*.02)score-=8;lines.push({text,key:k,avgConf:avg,score,bbox:{x:l,y:t,w:width,h:height}});}return lines.sort((a,b)=>b.score-a.score);}
  function paddedBox(b,W,H){const px=Math.max(10,b.w*.10),py=Math.max(8,b.h*.75);return clampBox({x:b.x-px,y:b.y-py,w:b.w+2*px,h:b.h+2*py},W,H);}
  async function locateLine(w,sign,type,onProgress){onProgress?.(10,'yazı alanı aranıyor');await w.setParameters({tessedit_pageseg_mode:'11',preserve_interword_spaces:'1',user_defined_dpi:'300'});const res=await w.recognize(sign,{}, {text:true,tsv:true}),words=parseTSV(res?.data?.tsv||''),lines=groupLines(words,sign.width,sign.height,type);return{line:lines[0]||null,alternates:lines.slice(1,4),located:!!lines.length};}
  function visualBands(sign,type){const W=sign.width,H=sign.height,g=grayscaleData(sign),row=new Float32Array(H);for(let y=1;y<H-1;y++){let s=0,n=0;for(let x=Math.round(W*.05);x<W*.95;x++){if(!insideShape(x,y,W,H,type))continue;const p=y*W+x;s+=Math.abs(g[p+1]-g[p-1])+.35*Math.abs(g[p+W]-g[p-W]);n++;}row[y]=s/Math.max(1,n);}const sm=new Float32Array(H);for(let y=0;y<H;y++){let s=0,n=0;for(let k=-5;k<=5;k++){const yy=y+k;if(yy>=0&&yy<H){s+=row[yy];n++;}}sm[y]=s/n;}const peaks=[...Array(H).keys()].filter(y=>y>H*.14&&y<H*.86).sort((a,b)=>{const ca=1-Math.abs(a-H/2)/(H/2),cb=1-Math.abs(b-H/2)/(H/2);return(sm[b]*(.78+.22*cb))-(sm[a]*(.78+.22*ca));}),picked=[];for(const y of peaks){if(picked.every(p=>Math.abs(p-y)>H*.16)){picked.push(y);if(picked.length===2)break;}}const out=picked.map((y,i)=>{const bh=H*(i?0.26:0.30);return clampBox({x:W*.055,y:y-bh/2,w:W*.89,h:bh},W,H);});out.push(clampBox({x:W*.06,y:H*.34,w:W*.88,h:H*.32},W,H));return out;}
  function iou(a,b){const x1=Math.max(a.x,b.x),y1=Math.max(a.y,b.y),x2=Math.min(a.x+a.w,b.x+b.w),y2=Math.min(a.y+a.h,b.y+b.h),inter=Math.max(0,x2-x1)*Math.max(0,y2-y1);return inter/Math.max(1,a.w*a.h+b.w*b.h-inter);}
  async function recognizeTight(w,canvas,psm=7){await w.setParameters({tessedit_pageseg_mode:String(psm),preserve_interword_spaces:'1',user_defined_dpi:'300',tessedit_char_whitelist:"ABCDEFGHIJKLMNOPQRSTUVWXYZÇĞİÖŞÜabcdefghijklmnopqrstuvwxyzçğıöşü0123456789&+.-/' "});const r=await w.recognize(canvas),text=normalize(r?.data?.text||''),confidence=Number(r?.data?.confidence||0);return{text,confidence,key:key(text)};}
  function lev(a,b){a=a||'';b=b||'';const d=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=d[0];d[0]=i;for(let j=1;j<=b.length;j++){const tmp=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=tmp;}}return d[b.length];}
  function similarity(a,b){if(!a&&!b)return 1;return 1-lev(a,b)/Math.max(1,a.length,b.length);}
  function plausible(r){return r&&r.key.length>=3&&r.key.length<=40&&alphaRatio(r.text)>=.72&&r.confidence>=5;}
  function choose(cands,located){const usable=cands.filter(plausible);if(!usable.length)return{best:{text:'',confidence:0,key:''},score:0,validated:false,consensus:0};const groups=[];for(const r of usable){let g=groups.find(x=>x.key===r.key);if(!g){g={key:r.key,items:[]};groups.push(g);}g.items.push(r);}for(const g of groups){g.items.sort((a,b)=>b.confidence-a.confidence);const best=g.items[0],sources=new Set(g.items.map(x=>x.source+'|'+x.variant+'|'+x.angle));g.best=best;g.count=sources.size;g.rank=best.confidence+Math.min(30,(g.count-1)*13)+Math.min(10,best.key.length*.55)+(located?4:0);}groups.sort((a,b)=>b.rank-a.rank);let g=groups[0],best=g.best,score=0,consensus=g.count;if(g.count>=2&&best.confidence>=72)score=100;else if(g.count>=2&&best.confidence>=55)score=Math.min(96,82+Math.round((best.confidence-55)*.45));else score=Math.min(89,Math.round(best.confidence*.72+Math.min(18,best.key.length*.9)+(located?8:3)));if(groups.length>1&&g.count<2){const alt=groups[1],sim=similarity(g.key,alt.key);if(sim>=.88&&alt.best.confidence>=40){score=Math.max(score,88);consensus=2;}}return{best,score,validated:score>=92,consensus};}
  async function run(photoData,shape,onProgress){const img=await loadImage(photoData),w=await ensure(onProgress);let box=shape?.bbox||{x:img.width*.08,y:img.height*.15,w:img.width*.84,h:img.height*.7};box=clampBox(box,img.width,img.height);let sign=crop(img,box,1.8);sign=maskSign(sign,shape?.shapeType);const locator=await locateLine(w,sign,shape?.shapeType,onProgress);const boxes=[];if(locator.line)boxes.push({box:paddedBox(locator.line.bbox,sign.width,sign.height),source:'tespit'});for(const vb of visualBands(sign,shape?.shapeType)){if(boxes.every(x=>iou(x.box,vb)<.74))boxes.push({box:vb,source:'görsel bant'});if(boxes.length>=4)break;}const cands=[];for(let i=0;i<Math.min(3,boxes.length);i++){const item=boxes[i],tight=crop(sign,item.box,2.35);onProgress?.(22+i*18,`yazı testi ${i+1}/3`);for(const job of [{img:tight,psm:7,variant:'doğal'},{img:enhance(tight,'contrast'),psm:8,variant:'kontrast'},{img:enhance(tight,'otsu'),psm:8,variant:'otsu'}]){const r=await recognizeTight(w,job.img,job.psm);r.source=item.source;r.variant=job.variant;r.angle=0;if(plausible(r))cands.push(r);}}
    let pick=choose(cands,locator.located);if(!pick.validated){let target=boxes[0]?.box||{x:sign.width*.06,y:sign.height*.34,w:sign.width*.88,h:sign.height*.32};if(boxes.length>1){const bySource=cands.slice().sort((a,b)=>b.confidence-a.confidence)[0];if(bySource){const idx=boxes.findIndex(x=>x.source===bySource.source);if(idx>=0)target=boxes[idx].box;}}const base=crop(sign,target,2.45);for(const ang of [-12,-8,8,12]){onProgress?.(78+Math.round((ang+12)/24*16),'eğim düzeltme');for(const job of [{img:enhance(rotate(base,ang),'contrast'),psm:7,variant:'eğim-kontrast'},{img:enhance(rotate(base,ang),'otsu'),psm:8,variant:'eğim-otsu'}]){const r=await recognizeTight(w,job.img,job.psm);r.source='eğim';r.variant=job.variant;r.angle=ang;if(plausible(r))cands.push(r);}pick=choose(cands,locator.located);if(pick.validated)break;}}
    const uniq=[],seen=new Set();for(const r of cands.slice().sort((a,b)=>b.confidence-a.confidence)){if(!seen.has(r.key)){seen.add(r.key);uniq.push(r);}}for(const l of locator.alternates||[]){if(!seen.has(l.key)){seen.add(l.key);uniq.push({text:l.text,confidence:l.avgConf,key:l.key,source:'alternatif'});}}
    onProgress?.(100,pick.validated?'doğrulandı':'kontrol gerekli');return{text:pick.best.text,confidence:pick.score,validationScore:pick.score,rawConfidence:Math.round(pick.best.confidence||0),validated:pick.validated,consensus:pick.consensus,candidates:uniq.slice(0,5),textRegion:locator.located?'localized+visual':'visual',locatorConfidence:Math.round(locator.line?.avgConf||0),version:'9.1-multiband-deskew'};
  }
  window.TabelaOCR8={run,prewarm,version:'9.1-multiband-deskew'};
})();