(() => {
  let worker=null,workerPromise=null;
  const loadImage=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src;});
  const cv=(w,h)=>{const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c;};
  function clampBox(b,W,H){const x=Math.max(0,Math.min(W-1,b.x||0)),y=Math.max(0,Math.min(H-1,b.y||0));return{x,y,w:Math.max(1,Math.min(W-x,b.w||W)),h:Math.max(1,Math.min(H-y,b.h||H))};}
  function crop(img,b,scale=2){b=clampBox(b,img.width,img.height);const c=cv(b.w*scale,b.h*scale),x=c.getContext('2d');x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.drawImage(img,b.x,b.y,b.w,b.h,0,0,c.width,c.height);return c;}
  function maskSign(src,type){if(!['circle','oval'].includes(type))return src;const c=cv(src.width,src.height),x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.save();x.beginPath();x.ellipse(c.width/2,c.height/2,c.width*.47,c.height*.47,0,0,Math.PI*2);x.clip();x.drawImage(src,0,0);x.restore();return c;}
  function enhance(src,mode='contrast'){const c=cv(src.width,src.height),x=c.getContext('2d',{willReadFrequently:true});x.drawImage(src,0,0);const im=x.getImageData(0,0,c.width,c.height),d=im.data;let mean=0;for(let i=0;i<d.length;i+=4)mean+=.299*d[i]+.587*d[i+1]+.114*d[i+2];mean/=Math.max(1,d.length/4);for(let i=0;i<d.length;i+=4){let g=.299*d[i]+.587*d[i+1]+.114*d[i+2];g=Math.max(0,Math.min(255,(g-mean)*(mode==='threshold'?2.35:1.9)+128));if(mode==='threshold')g=g>145?255:0;d[i]=d[i+1]=d[i+2]=g;}x.putImageData(im,0,0);return c;}
  function clean(s){return(s||'').replace(/[|_~`^]+/g,' ').replace(/[“”]/g,'"').replace(/\s+/g,' ').replace(/^[^A-Za-zÇĞİÖŞÜçğıöşü0-9]+|[^A-Za-zÇĞİÖŞÜçğıöşü0-9]+$/g,'').trim();}
  function normalize(s){const t=clean(s),p=t.split(/\s+/).filter(Boolean);if(p.length>=3&&p.filter(x=>/^[A-Za-zÇĞİÖŞÜçğıöşü0-9]{1,2}$/.test(x)).length/p.length>.72&&p.join('').length<=36)return p.join('');return t;}
  function key(s){return normalize(s).toLocaleUpperCase('tr-TR').replace(/[^A-ZÇĞİÖŞÜ0-9]/g,'');}
  function alphaRatio(s){const a=[...(s||'')],n=a.filter(ch=>/[A-Za-zÇĞİÖŞÜçğıöşü0-9]/.test(ch)).length;return n/Math.max(1,a.length);}
  async function ensure(onProgress){if(worker)return worker;if(workerPromise)return workerPromise;if(!window.Tesseract)throw new Error('OCR motoru yüklenemedi. İnternet bağlantısını kontrol edin.');workerPromise=Tesseract.createWorker('tur+eng',1,{logger:m=>{if(onProgress&&typeof m.progress==='number')onProgress(Math.round(m.progress*100),m.status||'hazırlanıyor')}}).then(w=>{worker=w;return w});return workerPromise;}
  async function prewarm(){try{await ensure();return true}catch{return false}}
  function parseTSV(tsv){if(!tsv)return[];const rows=tsv.split(/\r?\n/).filter(Boolean);if(rows.length<2)return[];const h=rows[0].split('\t'),ix=n=>h.indexOf(n),out=[];for(const row of rows.slice(1)){const a=row.split('\t');if(Number(a[ix('level')])!==5)continue;const text=clean(a.slice(ix('text')).join(' '));const conf=Number(a[ix('conf')]);if(!text||!Number.isFinite(conf)||conf<10)continue;out.push({text,conf,left:+a[ix('left')],top:+a[ix('top')],width:+a[ix('width')],height:+a[ix('height')],block:a[ix('block_num')],par:a[ix('par_num')],line:a[ix('line_num')]});}return out;}
  function insideShape(cx,cy,W,H,type){if(!['circle','oval'].includes(type))return true;const nx=(cx-W/2)/(W*.47),ny=(cy-H/2)/(H*.47);return nx*nx+ny*ny<=1;}
  function groupLines(words,W,H,type){const m=new Map();for(const w of words){const cx=w.left+w.width/2,cy=w.top+w.height/2;if(!insideShape(cx,cy,W,H,type))continue;const k=`${w.block}:${w.par}:${w.line}`;if(!m.has(k))m.set(k,[]);m.get(k).push(w);}const lines=[];for(const ws of m.values()){ws.sort((a,b)=>a.left-b.left);let l=Infinity,t=Infinity,r=-1,b=-1,cs=0;for(const w of ws){l=Math.min(l,w.left);t=Math.min(t,w.top);r=Math.max(r,w.left+w.width);b=Math.max(b,w.top+w.height);cs+=w.conf;}const text=normalize(ws.map(x=>x.text).join(' ')),k=key(text);if(k.length<3||k.length>40)continue;const width=r-l,height=b-t,cx=(l+r)/2,cy=(t+b)/2,avg=cs/ws.length,wr=width/W,hr=height/H,center=1-Math.min(1,Math.hypot((cx-W/2)/(W/2),(cy-H/2)/(H/2))/1.414),edge=Math.min(l,t,W-r,H-b),punct=1-alphaRatio(text);let score=avg+center*24+Math.min(16,k.length*1.2)+Math.min(12,wr*20)-punct*35;if(hr<.035||hr>.55)score-=22;if(wr<.08)score-=12;if(edge<Math.min(W,H)*.025)score-=10;if(['circle','oval'].includes(type)&&!insideShape(cx,cy,W,H,type))score-=50;lines.push({text,key:k,avgConf:avg,score,bbox:{x:l,y:t,w:width,h:height}});}return lines.sort((a,b)=>b.score-a.score);}
  function paddedBox(b,W,H){const px=Math.max(8,b.w*.07),py=Math.max(7,b.h*.55);return clampBox({x:b.x-px,y:b.y-py,w:b.w+2*px,h:b.h+2*py},W,H);}
  async function locateLine(w,sign,type,onProgress){onProgress?.(12,'yazı alanı bulunuyor');await w.setParameters({tessedit_pageseg_mode:'11',preserve_interword_spaces:'1',user_defined_dpi:'300'});const res=await w.recognize(sign,{}, {text:true,tsv:true});const words=parseTSV(res?.data?.tsv||'');const lines=groupLines(words,sign.width,sign.height,type);if(lines.length)return{line:lines[0],alternates:lines.slice(1,4),located:true};return{line:null,alternates:[],located:false};}
  async function recognizeTight(w,canvas,psm=7){await w.setParameters({tessedit_pageseg_mode:String(psm),preserve_interword_spaces:'1',user_defined_dpi:'300',tessedit_char_whitelist:"ABCDEFGHIJKLMNOPQRSTUVWXYZÇĞİÖŞÜabcdefghijklmnopqrstuvwxyzçğıöşü0123456789&+.-/' "});const r=await w.recognize(canvas);const text=normalize(r?.data?.text||''),confidence=Number(r?.data?.confidence||0);return{text,confidence,key:key(text)};}
  function lev(a,b){a=a||'';b=b||'';const d=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=d[0];d[0]=i;for(let j=1;j<=b.length;j++){const tmp=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=tmp;}}return d[b.length];}
  function similarity(a,b){if(!a&&!b)return 1;return 1-lev(a,b)/Math.max(1,a.length,b.length);}
  function plausible(r){return r&&r.key.length>=3&&r.key.length<=40&&alphaRatio(r.text)>=.72;}
  function validation(locator,a,b){const usable=[a,b].filter(plausible);if(!usable.length)return{score:0,validated:false,consensus:0,best:{text:'',confidence:0,key:''}};usable.sort((x,y)=>y.confidence-x.confidence);const best=usable[0];let score=0;score+=locator.located?25:5;score+=Math.min(35,Math.max(0,best.confidence)*.35);score+=plausible(best)?10:0;let consensus=1,sim=0;if(usable.length>1){sim=similarity(usable[0].key,usable[1].key);if(usable[0].key===usable[1].key){consensus=2;score+=30;}else if(sim>=.88){consensus=2;score+=22;}else if(sim>=.72)score+=10;}if(locator.line?.avgConf>=45)score+=5;score=Math.max(0,Math.min(100,Math.round(score)));if(consensus===2&&usable[0].key===usable[1].key&&locator.located&&best.confidence>=80)score=100;return{score,validated:score>=90,consensus,best,similarity:sim};}
  async function run(photoData,shape,onProgress){const img=await loadImage(photoData),w=await ensure(onProgress);let box=shape?.bbox||{x:img.width*.08,y:img.height*.15,w:img.width*.84,h:img.height*.7};box=clampBox(box,img.width,img.height);let sign=crop(img,box,1.6);sign=maskSign(sign,shape?.shapeType);const locator=await locateLine(w,sign,shape?.shapeType,onProgress);let lineBox;if(locator.line)lineBox=paddedBox(locator.line.bbox,sign.width,sign.height);else lineBox={x:sign.width*.08,y:sign.height*.30,w:sign.width*.84,h:sign.height*.40};const tight=crop(sign,lineBox,2.2);onProgress?.(48,'yazı doğrulanıyor 1/2');const a=await recognizeTight(w,tight,7);onProgress?.(72,'yazı doğrulanıyor 2/2');const b=await recognizeTight(w,enhance(tight,'contrast'),7);let v=validation(locator,a,b);let extra=null;if(!v.validated&&v.score<82){onProgress?.(86,'son kontrol');extra=await recognizeTight(w,enhance(tight,'threshold'),7);const options=[a,b,extra].filter(plausible).sort((x,y)=>y.confidence-x.confidence);if(options.length>=2){let bestPair=[options[0],options[1]],bestSim=similarity(options[0].key,options[1].key);for(let i=0;i<options.length;i++)for(let j=i+1;j<options.length;j++){const s=similarity(options[i].key,options[j].key);if(s>bestSim){bestSim=s;bestPair=[options[i],options[j]];}}v=validation(locator,bestPair[0],bestPair[1]);}}
    const raw=[a,b,extra].filter(plausible).sort((x,y)=>y.confidence-x.confidence);const display=[];const seen=new Set();for(const r of raw){if(!seen.has(r.key)){seen.add(r.key);display.push(r);}}for(const l of locator.alternates||[]){if(!seen.has(l.key)){seen.add(l.key);display.push({text:l.text,confidence:l.avgConf,key:l.key});}}
    onProgress?.(100,v.validated?'doğrulandı':'kontrol gerekli');return{text:v.best.text,confidence:v.score,validationScore:v.score,rawConfidence:Math.round(v.best.confidence||0),validated:v.validated,consensus:v.consensus,candidates:display.slice(0,4),textRegion:locator.located?'localized':'fallback',locatorConfidence:Math.round(locator.line?.avgConf||0),version:'9.0-localize'};
  }
  window.TabelaOCR8={run,prewarm,version:'9.0-localize'};
})();