(() => {
  let worker=null,workerPromise=null;
  const loadImage=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src;});
  const cv=(w,h)=>{const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c;};
  function crop(img,b,scale=2.2){const c=cv(b.w*scale,b.h*scale),x=c.getContext('2d');x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.drawImage(img,b.x,b.y,b.w,b.h,0,0,c.width,c.height);return c;}
  function enhance(src,threshold=null){const c=cv(src.width,src.height),x=c.getContext('2d',{willReadFrequently:true});x.drawImage(src,0,0);const im=x.getImageData(0,0,c.width,c.height),d=im.data;let m=0;for(let i=0;i<d.length;i+=4)m+=.299*d[i]+.587*d[i+1]+.114*d[i+2];m/=Math.max(1,d.length/4);for(let i=0;i<d.length;i+=4){let g=.299*d[i]+.587*d[i+1]+.114*d[i+2];g=Math.max(0,Math.min(255,(g-m)*2.15+128));if(threshold!==null)g=g>threshold?255:0;d[i]=d[i+1]=d[i+2]=g;}x.putImageData(im,0,0);return c;}
  function clean(s){return (s||'').replace(/[|_~`^]+/g,' ').replace(/\s+/g,' ').replace(/^[^A-Za-zÇĞİÖŞÜçğıöşü0-9]+|[^A-Za-zÇĞİÖŞÜçğıöşü0-9]+$/g,'').trim();}
  function normalize(s){const t=clean(s),parts=t.split(/\s+/).filter(Boolean);if(parts.length>=3&&parts.filter(x=>/^[A-Za-zÇĞİÖŞÜçğıöşü0-9]{1,2}$/.test(x)).length/parts.length>.72&&parts.join('').length<=32)return parts.join('');return t;}
  function key(s){return normalize(s).toLocaleUpperCase('tr-TR').replace(/[^A-ZÇĞİÖŞÜ0-9]/g,'');}
  async function ensure(onProgress){if(worker)return worker;if(workerPromise)return workerPromise;if(!window.Tesseract)throw new Error('OCR motoru yüklenemedi. İnternet bağlantısını kontrol edin.');workerPromise=Tesseract.createWorker('tur+eng',1,{logger:m=>{if(onProgress&&typeof m.progress==='number')onProgress(Math.round(m.progress*100),m.status||'hazırlanıyor')}}).then(w=>{worker=w;return w});return workerPromise;}
  function bandScores(sign){const x=sign.getContext('2d',{willReadFrequently:true}),im=x.getImageData(0,0,sign.width,sign.height),d=im.data,w=sign.width,h=sign.height,g=new Uint8Array(w*h);for(let i=0,p=0;i<d.length;i+=4,p++)g[p]=Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]);const row=new Float32Array(h);for(let y=1;y<h-1;y++){let s=0;for(let xx=1;xx<w-1;xx++){const p=y*w+xx;s+=Math.abs(g[p+1]-g[p-1])+Math.abs(g[p+w]-g[p-w]);}row[y]=s/Math.max(1,w-2);}const smooth=new Float32Array(h);for(let y=0;y<h;y++){let s=0,n=0;for(let k=-4;k<=4;k++){const yy=y+k;if(yy>=0&&yy<h){s+=row[yy];n++;}}smooth[y]=s/n;}const peaks=[...Array(h).keys()].sort((a,b)=>smooth[b]-smooth[a]);const picks=[];for(const y of peaks){if(picks.every(p=>Math.abs(p-y)>h*.18)){picks.push(y);if(picks.length===3)break;}}return picks;}
  function bandBox(signBox,signCanvas,center,frac=.32){const h=Math.max(signCanvas.height*.18,signCanvas.height*frac),y=Math.max(0,Math.min(signCanvas.height-h,center-h/2));const sy=signBox.h/signCanvas.height;return {x:signBox.x,y:signBox.y+y*sy,w:signBox.w,h:h*sy};}
  async function recognize(w,canvas,psm){await w.setParameters({tessedit_pageseg_mode:String(psm),preserve_interword_spaces:'1',user_defined_dpi:'300'});const r=await w.recognize(canvas),text=normalize(r?.data?.text||''),confidence=Number(r?.data?.confidence||0);return {text,confidence,key:key(text)};}
  function valid(r){return r.key.length>=3&&r.key.length<=40;}
  async function prewarm(){try{await ensure();return true}catch{return false}}
  async function run(photoData,shape,onProgress){const img=await loadImage(photoData),w=await ensure(onProgress);let box=shape?.bbox||{x:img.width*.08,y:img.height*.15,w:img.width*.84,h:img.height*.7};box={x:Math.max(0,box.x),y:Math.max(0,box.y),w:Math.min(img.width-Math.max(0,box.x),box.w),h:Math.min(img.height-Math.max(0,box.y),box.h)};const sign=crop(img,box,1.4),peaks=bandScores(sign),cands=[];const jobs=[];
    if(['circle','oval','triangle','polygon','freeform'].includes(shape?.shapeType))jobs.push({canvas:sign,psm:11,label:'serbest yazı'});
    for(const p of peaks.slice(0,2)){const bb=bandBox(box,sign,p,.30);const b=crop(img,bb,2.5);jobs.push({canvas:b,psm:7,label:'yazı bandı'});jobs.push({canvas:enhance(b,null),psm:7,label:'kontrast'});}
    if(!jobs.length){const b=crop(img,box,2);jobs.push({canvas:b,psm:7,label:'hızlı'});}
    for(let i=0;i<Math.min(4,jobs.length);i++){onProgress?.(Math.round(i/Math.min(4,jobs.length)*100),jobs[i].label);const r=await recognize(w,jobs[i].canvas,jobs[i].psm);if(valid(r))cands.push(r);if(r.confidence>=90&&valid(r)){onProgress?.(100,'hızlı doğrulama');return {text:r.text,confidence:Math.round(r.confidence),validated:true,consensus:1,candidates:[r],textRegion:'auto',version:'8.0-fast'};}if(cands.length>=2&&cands[cands.length-1].key===cands[cands.length-2].key){const best=cands[cands.length-1].confidence>=cands[cands.length-2].confidence?cands[cands.length-1]:cands[cands.length-2];onProgress?.(100,'iki sonuç uyuştu');return {text:best.text,confidence:Math.round(best.confidence),validated:true,consensus:2,candidates:cands,version:'8.0-fast'};}}
    cands.sort((a,b)=>b.confidence-a.confidence);const best=cands[0]||{text:'',confidence:0};onProgress?.(100,'tamamlandı');return {text:best.text,confidence:Math.round(best.confidence||0),validated:!!best.text&&best.confidence>=72,consensus:1,candidates:cands.slice(0,3),version:'8.0-fast'};
  }
  window.TabelaOCR8={run,prewarm,version:'8.0-fast'};
})();